[package]
name = "retro_player"
version = "0.1.0"
edition = "2024"

[dependencies]
retro_engine = { git = "https://github.com/The-Nice-One/PlaygroundProjects" }
kira = "0.10.4"
indexmap = "2.9.0"
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.5"
